# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f04b702d-c624-4a2a-81cf-8d42417c5f34";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f04b702d-c624-4a2a-81cf-8d42417c5f34".device = "/dev/disk/by-uuid/f04b702d-c624-4a2a-81cf-8d42417c5f34";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/66E4-63A0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b52960f9-7668-4347-bcf6-f8bdd9762fa5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
