# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-0df085c8-913c-4693-9bb0-bc8fac9ed4af";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0df085c8-913c-4693-9bb0-bc8fac9ed4af".device =
    "/dev/disk/by-uuid/0df085c8-913c-4693-9bb0-bc8fac9ed4af";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/105C-958F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-e1191ed0-f89e-483e-ae73-adecd9779a41"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
